<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<script
        src="https://code.jquery.com/jquery-3.2.1.slim.js"
        integrity="sha256-tA8y0XqiwnpwmOIl3SGAcFl2RvxHjA8qp0+1uCGmRmg="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container">
<h1>New Ticket</h1>
<form method="post" action="/ticket/new">
    <div class="form-group">
        <label for="title">Title</label>
        <input class="form-control" name="title" id="title" type="text" size="60" /><br />
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" name="description" id="description" rows="6" cols="80"></textarea><br />
    </div>
    <div class="form-group">
    <label for="component">Component</label>
    <select class="form-control" name="component">
        <option value=""></option>
<?php
foreach($components as $component): ?>
    <option value="<?=$component->getId()?>"><?=$component->getName()?></option>
<?php
endforeach;
?>
    </select><br />
    </div>
    <input type="hidden" name="<?=$name_key?>" value="<?=$name?>">
    <input type="hidden" name="<?=$value_key?>" value="<?=$value?>">
    <input type="submit" class="pure-button" value="Create" />
</form>
</div>
</body>
</html>


