<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<script
        src="https://code.jquery.com/jquery-3.2.1.slim.js"
        integrity="sha256-tA8y0XqiwnpwmOIl3SGAcFl2RvxHjA8qp0+1uCGmRmg="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container">
    <h1>All Tickets</h1>
    <p><a href="/ticket/new">Add new ticket</a></p>
    <form action="/ticket/search" method="get">
        <input type="text" name="q" placeholder="search Title" value="<?=$query ?>">
        <button class="pure-button" type="submit">search</button>
    </form>
    <?php
    if(count($tickets) > 0):
    ?>
    <table class="pure-table">
        <tr>
            <th>Title</th>
            <th>Component</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    <?php
        $odd = true;
        foreach($tickets as $ticket): ?>

            <tr <?=$odd ? "class=\"pure-table-odd\"" : ""; ?>>
            <td><?=$ticket->getTitle() ?></td>
            <td><?=$ticket->getComponent() ?></td>
            <td><?=$ticket->getShortDescription() ?> </td>
            <td>
                <a href="<?=$router->pathFor('ticket-detail', ['id' => $ticket->getId()])?>">view</a>
            </td>
        </tr>

    <?php
        $odd = $odd ? false : true;
        endforeach; ?>
    </table>
    <?php else: ?>
    <p>No current tickets</p>
    <?php endif; ?>
</div>
</body>
</html>

